[build-system]
requires = [ 'setuptools>=61.0', 'wheel' ]
build-backend = 'setuptools.build_meta'

[project]
name = 'immobiliare'
version = '0.1.0'

[tool.setuptools]
package-dir = {'' = 'src'}
packages = ['immobiliare']

[tool.setuptools.package-data]
'immobiliare.config' = ['config.yaml']